// Idealmente aquí iría el código para extraer toda la información sobre
// los productos con toda su información en un objeto

export const productos = [
    {
        id: 39100057,
        descripcion: "Cronch Flakes",
        marca: "Alfonzo Rivas",
        presentacion: "Bolsa",
        medida: "300 gr",
        precio: 5,
        descuento: 0,
        cnt: 1,
    },
    {
        id: 12087277,
        descripcion: "Samba Fresa",
        marca: "Savoy",
        presentacion: "Display",
        medida: "32 gr",
        precio: 2.5,
        descuento: 10,
        cnt: 26,
    },
    {
        id: 12087277,
        descripcion: "Samba Fresa",
        marca: "Savoy",
        presentacion: "Display",
        medida: "32 gr",
        precio: 2.5,
        descuento: 10,
        cnt: 26,
    },
    {
        id: 12087277,
        descripcion: "Samba Fresa",
        marca: "Savoy",
        presentacion: "Display",
        medida: "32 gr",
        precio: 2.5,
        descuento: 10,
        cnt: 26,
    },
    {
        id: 441076,
        descripcion: "Nestea de Durazno",
        marca: "Nestea",
        presentacion: "Display",
        medida: "90 gr",
        precio: 3,
        descuento: 5,
        cnt: 12,
    },
]