// Idealmente aquí iría el código para extraer toda la información sobre
// los productos con toda su información en un objeto

export const productos = [
    {
        id: 39100057,
        empresa: 2,
        marca: "Alfonzo Rivas",
        descrip: "Cronch Flakes",
        presentcn: "Bolsa",
        peso: 300,
        undMedida: "gr",
        precio: 5,
        cnt: 1,
        estado: "Activo",
        categoria: "Cereales",
        descuento: 0,
    },
    {
        id: 12124100,
        empresa: 1,
        marca: "Savoy",
        descrip: "Cri-Cri",
        presentcn: "Display",
        peso: 123,
        undMedida: "gr",
        precio: 1.25,
        cnt: 5,
        estado: "Activo",
        categoria: "Cereales",
        descuento: 0,
    },
    {
        id: 12087277,
        empresa: 1,
        marca: "Savoy",
        descrip: "Samba Fresa",
        presentcn: "Display",
        peso: 32,
        undMedida: "gr",
        precio: 2.5,
        cnt: 26,
        estado: "Activo",
        categoria: "Confites",
        descuento: 10,
    },
    {
        id: 441076,
        empresa: 1,
        marca: "Nestea",
        descrip: "Nestea de Durazno",
        presentcn: "Display",
        peso: 90,
        undMedida: "gr",
        precio: 3,
        cnt: 12,
        estado: "Activo",
        categoria: "Bebida",
        descuento: 5,
    },
]