export const monedas = [
  { nombre: 'Bolívar', simbolo: 'Bs.', valorDolar: 33 },
  { nombre: 'Dólar', simbolo: '$' }
]

export const marcas = [
  {
    id: 1,
    label: 'Nestlé Venezuela, S.A'
  },
  {
    id: 2,
    label: 'Alfonzo Rivas & Cia, C.A.'
  },
  {
    id: 3,
    label: 'PEPSICO Alimentos, S.C.A'
  },
  {
    id: 4,
    label: 'Envaprimol'
  },
  {
    id: 5,
    label: 'El Tunal, C.A.'
  },
  {
    id: 6,
    label: 'Plumrose Latinoamericana, C.A.'
  },
  {
    id: 7,
    label: 'Gombi Ind. Alimenticias, C.A.'
  },
  {
    id: 8,
    label: 'Ind. Lacteas Torondoy, C.A.'
  },
  {
    id: 9,
    label: 'General de Alimentos Nisa, C.A.'
  }
]

export const productos = [
  {
    id: 39100057,
    empresa: 2,
    marca: 'Alfonzo Rivas',
    descripcion: 'Cronch Flakes',
    display: 'Bolsa',
    medida: '300 Gr',
    categoria: 'Cereales',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo',
    descuento: 0
  },
  {
    id: 39400123,
    empresa: 2,
    marca: 'Alfonzo Rivas',
    descripcion: 'Fruty Aros',
    display: 'Bolsa',
    medida: '25 Gr',
    categoria: 'Cereales',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo',
    descuento: 30
  },
  {
    id: 144400204,
    empresa: 2,
    marca: 'McCormick',
    descripcion: 'Hojas de albahaca',
    display: 'Frasco',
    medida: '16 Gr',
    categoria: 'Infusiones',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo',
    descuento: 15
  },
  {
    id: 141102208,
    empresa: 2,
    marca: 'McCormick',
    descripcion: 'Curry',
    display: 'Frasco',
    medida: '16 Gr',
    categoria: 'Sazonadoras',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo',
    descuento: 0
  },
  {
    id: 141103205,
    empresa: 2,
    marca: 'McCormick',
    descripcion: 'Oregano Entero',
    display: 'Frasco',
    medida: '16 Gr',
    categoria: 'Sazonadoras',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo',
    descuento: 0
  },
  {
    id: 11061,
    empresa: 6,
    marca: 'PLUMROSE',
    descripcion: 'Endiablado',
    display: 'Abre-Facil',
    medida: '110 Gr',
    categoria: 'enlatados',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo',
    descuento: 0
  },
  {
    id: 11060,
    empresa: 6,
    marca: 'PLUMROSE',
    descripcion: 'Endiablado',
    display: 'Abre-Facil',
    medida: '60 Gr',
    categoria: 'enlatados',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12423747,
    empresa: 1,
    marca: 'Nestlé',
    descripcion: 'Postre Cacao en Polvo',
    display: 'Bolsa',
    medida: '200 Gr',
    categoria: 'Profesional',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo',
    descuento: 0
  },
  {
    id: 12320237,
    empresa: 1,
    marca: 'Nestlé',
    descripcion: 'Bebida Achocolatada',
    display: 'Bolsa',
    medida: '1,600 Kg',
    categoria: 'Profesional',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo',
    descuento: 10
  },
  {
    id: 12300949,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Nescafé',
    display: 'NPRO vaso papel',
    medida: '6 Oz',
    categoria: 'Profesional',
    cant: '25 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 70115795,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Café Soluble Tradiciñon',
    display: 'Frasco',
    medida: '85 Gr',
    categoria: 'Profesional',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 70115796,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Café Soluble Tradiciñon',
    display: 'Frasco',
    medida: '170 Gr',
    categoria: 'Profesional',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12417147,
    empresa: 'Nestlé',
    marca: 'Maggi',
    descripcion: 'Caldo de Pollo',
    display: 'Bolsa',
    medida: '480 Gr',
    categoria: 'Profesional',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12089217,
    empresa: 'Nestlé',
    marca: 'Nestea   ',
    descripcion: 'Nestea de Limón',
    display: 'Bolsa',
    medida: '450 Gr',
    categoria: 'Bebida',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12089218,
    empresa: 'Nestlé',
    marca: 'Nestea   ',
    descripcion: 'Nestea de Durazno',
    display: 'Bolsa',
    medida: '450 Gr',
    categoria: 'Bebida',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12089212,
    empresa: 'Nestlé',
    marca: 'Nestea   ',
    descripcion: 'Nestea de Parchita',
    display: 'Bolsa',
    medida: '450 Gr',
    categoria: 'Bebida',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12476007,
    empresa: 'Nestlé',
    marca: 'Nestea   ',
    descripcion: 'Nestea de Limón',
    display: 'Bolsa',
    medida: '240 Gr',
    categoria: 'Bebida',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12436272,
    empresa: 'Nestlé',
    marca: 'Nestea   ',
    descripcion: 'Nestea de Durazno',
    display: 'Bolsa',
    medida: '240 Gr',
    categoria: 'Bebida',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12115370,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Cerelac',
    display: 'Bolsa',
    medida: '900 Gr',
    categoria: 'Bebida',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 1232027,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Cerelac',
    display: 'Bolsa',
    medida: '400 Gr',
    categoria: 'Bebida',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12392754,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Cerelac',
    display: 'Bolsa',
    medida: '100 Gr',
    categoria: 'Bebida',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12374159,
    empresa: 'Nestlé',
    marca: 'Nestum',
    descripcion: '3 Cereales',
    display: 'Bolsa',
    medida: '225 Gr',
    categoria: 'Bebida',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12374158,
    empresa: 'Nestlé',
    marca: 'Nestum',
    descripcion: 'Trigo Miel',
    display: 'Bolsa',
    medida: '225 Gr',
    categoria: 'Bebida',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12373491,
    empresa: 'Nestlé',
    marca: 'Nestum',
    descripcion: 'Arroz',
    display: 'Bolsa',
    medida: '225 Gr',
    categoria: 'Bebida',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12408998,
    empresa: 'Nestlé',
    marca: 'Nestum',
    descripcion: 'Arroz Maiz',
    display: 'Bolsa',
    medida: '225 Gr',
    categoria: 'Bebida',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12055359,
    empresa: 'Nestlé',
    marca: 'Savoy',
    descripcion: 'Mini Carre avellana',
    display: 'Display',
    medida: '25 Gr ',
    categoria: 'Bebida',
    cant: '16 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12377261,
    empresa: 'Nestlé',
    marca: 'Savoy',
    descripcion: '75 Años choco Oscuro',
    display: 'Display',
    medida: '100 Gr',
    categoria: 'Confites',
    cant: '10 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12087285,
    empresa: 'Nestlé',
    marca: 'Savoy',
    descripcion: 'Samba Chocolate',
    display: 'Display',
    medida: '32 Gr',
    categoria: 'Confites',
    cant: '20 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12352698,
    empresa: 'Nestlé',
    marca: 'Savoy',
    descripcion: 'Cremosa Navidad',
    display: 'Display',
    medida: '70 Gr',
    categoria: 'Confites',
    cant: '9 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12494646,
    empresa: 'Nestlé',
    marca: 'Savoy',
    descripcion: 'Choco Duó ',
    display: 'Display',
    medida: '130 Gr',
    categoria: 'Confites',
    cant: '5 Unidade',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12459638,
    empresa: 'Nestlé',
    marca: 'Savoy',
    descripcion: 'Especialidades',
    display: 'Display',
    medida: '251 Gr',
    categoria: 'Confites',
    cant: '15 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 15511465,
    empresa: 'Nestlé',
    marca: 'Savoy',
    descripcion: 'Carre Caramelo',
    display: 'Display',
    medida: '100 Gr',
    categoria: 'Confites',
    cant: '1 Display',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12285123,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Carnation',
    display: 'Lata',
    medida: '360 Gr',
    categoria: 'Leches culinarias',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12105675,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Crema de Leche',
    display: 'Lata',
    medida: '300 Gr',
    categoria: 'Leches culinarias',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 112267655,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Leche Condesada',
    display: 'lata',
    medida: '387 Gr',
    categoria: 'Leches culinarias',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 411541,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Moca',
    display: 'Lata',
    medida: '390 Gr',
    categoria: 'Leches culinarias',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12395887,
    empresa: 'Nestlé',
    marca: 'Gerber',
    descripcion: 'Gerber Pera',
    display: 'Envase',
    medida: '113 Gr',
    categoria: 'Nutrición',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12395334,
    empresa: 'Nestlé',
    marca: 'Gerber',
    descripcion: 'Gerber Manzana',
    display: 'Envase',
    medida: '113 Gr',
    categoria: 'Nutrición',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12395415,
    empresa: 'Nestlé',
    marca: 'Gerber',
    descripcion: 'Gerber Banana',
    display: 'Envase',
    medida: '113 Gr',
    categoria: 'Nutrición',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12453715,
    empresa: 'Nestlé',
    marca: 'Gerber',
    descripcion: 'Gerber Pera',
    display: 'Pouch      ',
    medida: '100 Gr',
    categoria: 'Nutrición',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12454228,
    empresa: 'Nestlé',
    marca: 'Gerber',
    descripcion: 'Gerber Manzana',
    display: 'Pouch      ',
    medida: '100 Gr',
    categoria: 'Nutrición',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12454118,
    empresa: 'Nestlé',
    marca: 'Gerber',
    descripcion: 'Gerber Banana',
    display: 'Pouch      ',
    medida: '100 Gr',
    categoria: 'Nutrición',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12131599,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Cocosette',
    display: 'Display',
    medida: '18*50 Gr ',
    categoria: 'Confites',
    cant: '12 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 447180,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Cocosette',
    display: 'Multipack',
    medida: '18*50 Gr ',
    categoria: 'Confites',
    cant: '4 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12131304,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Susy',
    display: 'Display',
    medida: '18*50 Gr ',
    categoria: 'Confites',
    cant: '12 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12328550,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Susy Choco2',
    display: 'Multipack',
    medida: '18*50 Gr ',
    categoria: 'Confites',
    cant: '4 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 447312,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Susy',
    display: 'Multipack',
    medida: '18*50 Gr ',
    categoria: 'Confites',
    cant: '4 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12328459,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Susy Choco 2',
    display: 'Display',
    medida: '18*50 Gr ',
    categoria: 'Confites',
    cant: '12 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12395820,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Samba Fresa',
    display: 'Multipack',
    medida: '128 Gr',
    categoria: 'Confites',
    cant: '4 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: '440662U',
    empresa: 'Nestlé',
    marca: 'Maggi',
    descripcion: 'Cubito de Pollo',
    display: 'Display',
    medida: '92 Gr',
    categoria: 'Caldos y Sazonadores',
    cant: '8 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: '440602U',
    empresa: 'Nestlé',
    marca: 'Maggi',
    descripcion: 'Cubito de Costilla',
    display: 'Display',
    medida: '88 Gr',
    categoria: 'Caldos y Sazonadores',
    cant: '8 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 15508414,
    empresa: 'Nestlé',
    marca: 'Maggi',
    descripcion: 'Cubito de Pollo',
    display: 'Display',
    medida: '4*2 Gr',
    categoria: 'Caldos y Sazonadores',
    cant: '70 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12408798,
    empresa: 'Nestlé',
    marca: 'Maggi',
    descripcion: 'Sopa de pollo con Fideos',
    display: 'Display',
    medida: '12*62 Gr',
    categoria: 'Caldos y Sazonadores',
    cant: '6 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12471270,
    empresa: 'Nestlé',
    marca: 'Maggi',
    descripcion: 'Sopa de Vegetales C/Pasta',
    display: 'Display',
    medida: '15*35 Gr',
    categoria: 'Caldos y Sazonadores',
    cant: '6 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12468357,
    empresa: 'Nestlé',
    marca: 'Maggi',
    descripcion: 'Caldo de Pollo',
    display: 'Display',
    medida: '138 Gr',
    categoria: 'Caldos y Sazonadores',
    cant: '12 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12492229,
    empresa: 'Nestlé',
    marca: 'Maggi',
    descripcion: 'Caldo de Pollo',
    display: 'Display',
    medida: '35 Gr',
    categoria: 'Caldos y Sazonadores',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12078729,
    empresa: 'Purina',
    marca: 'Purina',
    descripcion: 'Carne y pollo',
    display: 'Empaque',
    medida: '2 Kg',
    categoria: 'Alimentos para Perros',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12078732,
    empresa: 'Purina',
    marca: 'Purina',
    descripcion: 'Carne y pollo',
    display: 'Empaque',
    medida: '6 Kg',
    categoria: 'Alimentos para Perros',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 0,
    empresa: 'Purina',
    marca: 'Purina',
    descripcion: 'Carne y pollo',
    display: 'Empaque',
    medida: '8 Kg',
    categoria: 'Alimentos para Perros',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12486642,
    empresa: 'Purina',
    marca: 'K-Nina',
    descripcion: 'Carne, cereal y arroz',
    display: 'Empaque',
    medida: '1 Kg',
    categoria: 'Alimentos para Perros',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12063700,
    empresa: 'Purina',
    marca: 'K-Nina',
    descripcion: 'Carne, cereal y arroz',
    display: 'Empaque',
    medida: '2 Kg',
    categoria: 'Alimentos para Perros',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12331394,
    empresa: 'Purina',
    marca: 'K-Nina',
    descripcion: 'Carne, cereal y arroz',
    display: 'Empaque',
    medida: '4 Kg',
    categoria: 'Alimentos para Perros',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12429640,
    empresa: 'Purina',
    marca: 'K-Nina',
    descripcion: 'Pollo y Vegetales',
    display: 'Empaque',
    medida: '1 Kg',
    categoria: 'Alimentos para Perros',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12429630,
    empresa: 'Purina',
    marca: 'K-Nina',
    descripcion: 'Pollo y Vegetales',
    display: 'Empaque',
    medida: '1 Kg',
    categoria: 'Alimentos para Perros',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 20479316,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Leche Completa',
    display: 'Empaque',
    medida: '800 Gr',
    categoria: 'Lacteos',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12408122,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Forti Crece',
    display: 'Empaque',
    medida: '800 Gr',
    categoria: 'Lacteos',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12330657,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Svelty',
    display: 'Empaque',
    medida: '400 Gr',
    categoria: 'Lacteos',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12236369,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Rica Chicha',
    display: 'Empaque',
    medida: '400 Gr',
    categoria: 'Lacteos',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12527908,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Nutri Rinde',
    display: 'Empaque',
    medida: '400 Gr',
    categoria: 'Lacteos',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 101330,
    empresa: 'Paveca',
    marca: 'Rosal',
    descripcion: 'Soft Plus ',
    display: 'Empaque',
    medida: '400 Hojas C/u',
    categoria: 'Productos de limpieza',
    cant: '4 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 102026,
    empresa: 'Paveca',
    marca: 'Rosal',
    descripcion: 'Rosal Plus',
    display: 'Empaque',
    medida: '215 Hojas C/u',
    categoria: 'Productos de limpieza',
    cant: '4 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 101610,
    empresa: 'Paveca',
    marca: 'Rosal',
    descripcion: 'Rosal Plus',
    display: 'Empaque',
    medida: '600 Hojas C/u',
    categoria: 'Productos de limpieza',
    cant: '4 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 101225,
    empresa: 'Paveca',
    marca: 'Rosal',
    descripcion: 'Soft Plus ',
    display: 'Empaque',
    medida: '300 Hojas C/u',
    categoria: 'Productos de limpieza',
    cant: ' 4 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 300029505,
    empresa: 'Pepsico',
    marca: 'Frito Lay',
    descripcion: 'Platanitos',
    display: 'Bolsa',
    medida: '150 gr',
    categoria: 'Snacks',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 300029506,
    empresa: 'Pepsico',
    marca: 'Frito Lay',
    descripcion: 'Platanitos',
    display: 'Bolsa',
    medida: '300 Gr',
    categoria: 'Snacks',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 300029615,
    empresa: 'Pepsico',
    marca: 'Frito Lay',
    descripcion: 'Platanitos Ondulados',
    display: 'Manga',
    medida: '38 Gr',
    categoria: 'Snacks',
    cant: '12 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 300034800,
    empresa: 'Pepsico',
    marca: 'Frito Lay',
    descripcion: 'De todito',
    display: 'Manga',
    medida: '45 gr',
    categoria: 'Snacks',
    cant: '12 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 300034802,
    empresa: 'Pepsico',
    marca: 'Frito Lay',
    descripcion: 'De todito',
    display: 'Bolsa',
    medida: '130 Gr',
    categoria: 'Snacks',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 300034797,
    empresa: 'Pepsico',
    marca: 'Frito Lay',
    descripcion: 'De todito',
    display: 'Bolsa',
    medida: '400 Gr',
    categoria: 'Snacks',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 'PTS003',
    empresa: 'Quidy',
    marca: 'Quidy',
    descripcion: 'Soya',
    display: 'Botella',
    medida: '150 Cc',
    categoria: 'Salsas',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 'PTS01',
    empresa: 'Quidy',
    marca: 'Quidy',
    descripcion: 'Ajo',
    display: 'Botella',
    medida: '150 Cc',
    categoria: 'Salsas',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 'PTS002',
    empresa: 'Quidy',
    marca: 'Quidy',
    descripcion: 'Inglesa',
    display: 'Botella',
    medida: '150 Cc',
    categoria: 'Salsas',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 'PTA007',
    empresa: 'Quidy',
    marca: 'Quidy',
    descripcion: 'Passata',
    display: 'Botella',
    medida: '500 Gr',
    categoria: 'Salsas',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 'PTS021',
    empresa: 'Quidy',
    marca: 'Quidy',
    descripcion: 'Picante',
    display: 'Botella',
    medida: '300 Cc',
    categoria: 'Salsas',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 'PTA022',
    empresa: 'Quidy',
    marca: 'Quidy',
    descripcion: 'Picante',
    display: 'Botella',
    medida: '150 Cc',
    categoria: 'Salsas',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 'S306',
    empresa: 'San Simón',
    marca: 'San Simón',
    descripcion: 'Leche en Polvo',
    display: 'Bolsa',
    medida: '125 Gr',
    categoria: 'Lacteos',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 'S9958',
    empresa: 'San Simón',
    marca: 'Montaña Fresca',
    descripcion: 'Leche en Polvo',
    display: 'Bolsa',
    medida: '400 Gr',
    categoria: 'Lacteos',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 'S310',
    empresa: 'San Simón',
    marca: 'San Simón',
    descripcion: 'Choco Rico',
    display: 'Bolsa ',
    medida: '400 Gr',
    categoria: 'Lacteos',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 'S317',
    empresa: 'San Simón',
    marca: 'San Simón',
    descripcion: 'Chicha en Polvo',
    display: 'Bolsa',
    medida: '400 Gr',
    categoria: 'Lacteos',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 1701,
    empresa: 'Torondoy',
    marca: 'Torondoy',
    descripcion: 'Queso Venmetal',
    display: 'Panela ',
    medida: '3 K Aprox',
    categoria: 'Emburtidos',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 1704,
    empresa: 'Torondoy',
    marca: 'Torondoy',
    descripcion: 'Venmental Porción',
    display: 'Bola',
    medida: '1 K Aprox',
    categoria: 'Emburtidos',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 829,
    empresa: 'Torondoy',
    marca: 'Torondoy',
    descripcion: 'Leche Semi/Des en polvo',
    display: 'Bolsa',
    medida: '900 Gr',
    categoria: 'Lacteos',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 108,
    empresa: 'Torondoy',
    marca: 'Torondoy',
    descripcion: 'Queso Brosso',
    display: 'Panela ',
    medida: '3 K Aprox',
    categoria: 'Emburtidos',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 90008,
    empresa: 'Doña Flora',
    marca: 'Doña Flora',
    descripcion: 'Queso Pecorino',
    display: 'Bola',
    medida: '1 K Aprox',
    categoria: 'Emburtidos',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 90058,
    empresa: 'Doña Flora',
    marca: 'Doña Flora',
    descripcion: 'Queso Manchego',
    display: 'Bola',
    medida: '1 K Aprox',
    categoria: 'Emburtidos',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 300503,
    empresa: 'Vizcaya',
    marca: 'Vizcaya',
    descripcion: 'Avena',
    display: 'Bolsa',
    medida: '400 Gr',
    categoria: 'Avena',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 300502,
    empresa: 'Vizcaya',
    marca: 'Vizcaya',
    descripcion: 'Avena',
    display: 'Bolsa',
    medida: '200 Gr',
    categoria: 'Avena',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 300505,
    empresa: 'Vizcaya',
    marca: 'Vizcaya',
    descripcion: 'Avena',
    display: 'Bolsa',
    medida: '800 Gr',
    categoria: 'Avena',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 'SD0001',
    empresa: 'Sal del mar',
    marca: 'Sal del mar',
    descripcion: 'Sal Refinada',
    display: 'Bolsa',
    medida: '1 K',
    categoria: 'Condimento',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 'CB0001',
    empresa: 'Sal Bahia',
    marca: 'Bahia',
    descripcion: 'Sal Refinada',
    display: 'Bolsa',
    medida: '1 K',
    categoria: 'Condimento',
    cant: '1 Unidad',
    precio: '',
    estado: 'Activo'
  },
  {
    id: 12439382,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Cacao en polvo',
    display: 'Bolsa',
    medida: '1 K',
    categoria: 'Profesional',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12325329,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Cacao en polvo',
    display: 'Bolsa',
    medida: '20 Kg',
    categoria: 'Profesional',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12493325,
    empresa: 'Nestlé',
    marca: 'Maggi',
    descripcion: 'Crema de tomate',
    display: 'Display',
    medida: '72 Gr',
    categoria: 'Maggi',
    cant: '24 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12522720,
    empresa: 'Nestlé',
    marca: 'Savoy',
    descripcion: 'Samba ',
    display: 'Bolsa',
    medida: '16 Gr',
    categoria: 'Confetis',
    cant: '35 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 414629,
    empresa: 'Nestlé',
    marca: 'Savoy',
    descripcion: 'Charge',
    display: 'Display',
    medida: '40 Gr',
    categoria: 'Confetis',
    cant: '30 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 414216,
    empresa: 'Nestlé',
    marca: 'Savoy',
    descripcion: 'Chokito',
    display: 'Display',
    medida: '32 Gr',
    categoria: 'Confites',
    cant: '18 Unidades',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12531614,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: ' Nido Forticrece Deslactosada ',
    display: 'Lata',
    medida: '800 Gr',
    categoria: 'Lacteos',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12525984,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Cerelac',
    display: 'Bolsa',
    medida: '1 Kg',
    categoria: 'Lacteos',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12534588,
    empresa: 'Nestlé',
    marca: 'Nestlé',
    descripcion: 'Nestea Mix',
    display: 'Display',
    medida: '90 Gr',
    categoria: 'Nestea',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 12494349,
    empresa: 'Nestlé',
    marca: 'Purina',
    descripcion: 'Gatsy Pollo',
    display: 'Empaque',
    medida: '1 kg',
    categoria: 'Purina',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 'P10101',
    empresa: 'Covadonga',
    marca: 'Covadonga',
    descripcion: 'Jamón Cocido Superior',
    display: 'Empaque',
    medida: '3,8 Kg',
    categoria: 'Emburtidos',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 'P10201',
    empresa: 'Covadonga',
    marca: 'Covadonga',
    descripcion: 'Jamón Cocido Estandar',
    display: 'Empaque',
    medida: '3,8 Kg',
    categoria: 'Emburtidos',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  },
  {
    id: 'P10301',
    empresa: 'Covadonga',
    marca: 'Covadonga',
    descripcion: 'Pechuga Cocida de pavo ',
    display: 'Empaque',
    medida: '3,8 Kg',
    categoria: 'Emburtidos',
    cant: '1 Unidad',
    precio: 1,
    estado: 'Activo'
  }
]
